# vim: syntax=python tabstop=4 expandtab
"""
An Example workflow for NLSA analysis on a rayleigh benard convection dataset

Usage:
1. Specify path to NLSA root
2. Specify the configuration file
3. Run `snakemake <target>` from the shell

"""
import sys

#nlsapath = "https://bitbucket.org/nbren12/pynlsa/raw/master/" 
nlsapath="../../"

sys.path.insert(0, nlsapath)    # NLSA path

#
#  Include snakefiles
#


include: nlsapath + "/nlsa/recon.snakefile"
include: nlsapath + "/nlsa/diffusionmap.snakefile"

configfile: "nlsa.yaml"

subworkflow dataw:
    workdir: ""
    snakefile: "bin.snake"


data_template = \
"""
import xray

w = xray.open_dataset("{w}").w
w  -= w.mean('t')
"""

rule get_bin:
    input: w=dataw("bin.nc")
    output: "data.py"
    run: 
        with open(output[0],"w") as  f:
            f.write(data_template.format(w=input[0]))
